#!/bin/sh /etc/rc.common
# Alist v3.60.0 init script
USE_PROCD=1
START=99
STOP=10

PROG=/usr/bin/alist
DATA_DIR=/overlay/alist/data
TC_SCRIPT=/overlay/alist/tc_apply.sh

start_service() {
    procd_open_instance alist
    procd_set_param command $PROG server --data $DATA_DIR
    procd_set_param respawn
    procd_set_param stderr 1
    procd_set_param stdout 1
    procd_close_instance

    [ -x "$TC_SCRIPT" ] && $TC_SCRIPT apply
}

stop_service() {
    [ -x "$TC_SCRIPT" ] && $TC_SCRIPT clear
}
