#!/bin/sh /etc/rc.common
# USB swap with eMMC fallback
# Prefer swapfile on /dev/sda1; if USB is missing, fall back to eMMC swap partition.
START=38
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /etc/init.d/usb_swap_run
    procd_close_instance
}
